### ISSUE TITLE
Question about the setup

### ISSUE THREAD

**Issue by wlhee** [ridedott/grpc-web-cloud-run-issue#1]
Hi, is it expected that the envoy proxy is deployed to as a separate Cloud Run service (https://grpc-web-test-envoy-snpekwsqaa-ez.a.run.app) from the gRPC server (https://grpc-web-test-snpekwsqaa-ez.a.run.app)?

This setup has the same issue as "content-length: 0" will be added in the response sent by the gRPC server.

Would the actual setup be the envoy proxy and grpc server are built into one single container and deployed to Cloud Run? Envoy and the gRPC server communicates with localhost?

**Comment by merlinnot** [comment]
Hi! In this reproduction we were using a gRPC back end and an Envoy proxy deployed as two separate Cloud Run services. This setup works thanks to a host rewrite in the proxy (host is changed from the proxy URL to the back end URL).

**Comment by wlhee** [comment]
Yeah. I understand how the two Cloud Run services are chained together.

My question is more about in the actual production setup, is the envoy proxy deployed as a separate service that dispatches to different backend services, or it's deployed as a side car runs along side with the gRPC service?

It sounds like to me the envoy is a separate service?

**Comment by merlinnot** [comment]
Yes, Envoy is a separate service. We did consider running them inside of the same container (as Cloud Run doesn't support sidecars per se), but there are a lot of things that need to be taken care of for such a setup to actually work and we use Envoy solely for gRPC-web transcoding - in reality a large portion of the traffic (from clients that support gRPC natively) would travel through a proxy unnecessarily.

**Comment by wlhee** [comment]
Gotcha.  I will try something to see if we can workaround the content-length: 0 issue for empty response.

**Comment by wlhee** [comment]
I updated the envoy.yaml to remove the content-length header. It looks like once the C-L is removed, the js client starts working as expected. See the example PR: https://github.com/ridedott/grpc-web-cloud-run-issue/pull/2/commits/c734a5e8f0cc774d2f8fd9be4ba038c7670522e5

**Comment by wlhee** [comment]
Also filed an issue to grpc-web: https://github.com/grpc/grpc-web/issues/1101

**Comment by merlinnot** [comment]
Thanks! Do you think we should open an issue against Envoy as well?

**Comment by wlhee** [comment]
I am not very sure if this is a really bug in envoy, because a regular gRPC client works with C-L: 0 in the resposne.

**Comment by merlinnot** [comment]
I see. I don't have access to an internal issue mentioned here: https://github.com/grpc/grpc-web/issues/1101#issuecomment-869074714. I'll follow that issue for now. Again, many thanks for looking into this.

**Comment by wlhee** [comment]
No problem!

The internal issue is the same one your team filed.
